$(function(){ //DOM Ready

    function navigate(url)
    {
        window.location.href = url;
    }

    $(document).attr("title", "Casa Inteligente");
    content_width = (120 + 5) * 8 + 5
    $('.gridster').width(content_width)
    $(".gridster ul").gridster({
        widget_margins: [5, 5],
        widget_base_dimensions: [120, 120],
        avoid_overlapped_widgets: true,
        max_rows: 15,
        max_size_x: 8,
        shift_widgets_up: false
    }).data('gridster').disable();
    
    // Add Widgets

    var gridster = $(".gridster ul").gridster().data('gridster');
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseclock-default-clock" id="default-clock"><h1 class="date"data-bind="text: date, attr: {style: date_style}"></h1><h2 class="time" data-bind="text: time, attr: {style: time_style}"></h2></div></li>', 3, 2, 1, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-estore-cozinha" id="default-estore-cozinha"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 4, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-estore-sala" id="default-estore-sala"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 5, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-estore-mafalda" id="default-estore-mafalda"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 6, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-cover-estore-varanda-shelly" id="default-cover-estore-varanda-shelly"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 7, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseselect-default-input-select-estados-de-succao" id="default-input-select-estados-de-succao"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><div class="styled-select" data-bind="attr:{style: selectcontainer_style}">  <select data-bind="options: inputoptions, value: selectedoption, attr:{style: select_style}">  </select></div></div></li>', 2, 1, 4, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseselect-default-input-select-zonas-de-aspiracao" id="default-input-select-zonas-de-aspiracao"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><div class="styled-select" data-bind="attr:{style: selectcontainer_style}">  <select data-bind="options: inputoptions, value: selectedoption, attr:{style: select_style}">  </select></div></div></li>', 2, 1, 6, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-cover-estore-q-pequeno-shelly" id="default-cover-estore-q-pequeno-shelly"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 8, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-0x680ae2fffec92973-light" id="default-light-0x680ae2fffec92973-light"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 1, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-candeeiro-patio-1" id="default-light-candeeiro-patio-1"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 2, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-candeeiro-patio-2" id="default-light-candeeiro-patio-2"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 3, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-candeeiro-patio-3" id="default-light-candeeiro-patio-3"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 4, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-candeeiro-patio-4" id="default-light-candeeiro-patio-4"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 5, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-downlight-direito" id="default-light-downlight-direito"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 6, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-downlight-esquerdo" id="default-light-downlight-esquerdo"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 7, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-espelho-casa-de-banho" id="default-light-espelho-casa-de-banho"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 8, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-gateway-light-7811dcb38555" id="default-light-gateway-light-7811dcb38555"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 9, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-iluminacao-coberto" id="default-light-iluminacao-coberto"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 1, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-iluminacao-das-garagens" id="default-light-iluminacao-das-garagens"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 2, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-iluminacao-do-jardim" id="default-light-iluminacao-do-jardim"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 3, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-iluminacao-lateral" id="default-light-iluminacao-lateral"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 4, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-leds-armario" id="default-light-leds-armario"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 5, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-teto-casa-de-banho" id="default-light-teto-casa-de-banho"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 6, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-teto-da-sala" id="default-light-teto-da-sala"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 7, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-teto-quarto" id="default-light-teto-quarto"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 8, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-teto-quarto-mafalda" id="default-light-teto-quarto-mafalda"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 9, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-wc-pai" id="default-light-wc-pai"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 1, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-xiaomi-philips-zhirui" id="default-light-xiaomi-philips-zhirui"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 2, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-xiaomi-philips-zhirui-1" id="default-light-xiaomi-philips-zhirui-1"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 3, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-xiaomi-philips-zhirui-2" id="default-light-xiaomi-philips-zhirui-2"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 4, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-yeelight-color1-7811dc6b98cb" id="default-light-yeelight-color1-7811dc6b98cb"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 5, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-yeelight-color1-7811dc6b9b10" id="default-light-yeelight-color1-7811dc6b9b10"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 6, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-yeelight-color1-7811dce0fe41" id="default-light-yeelight-color1-7811dce0fe41"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 7, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-light-yeelight-color1-7811dce12676" id="default-light-yeelight-color1-7811dce12676"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 8, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basedisplay-default-sensor-temperatura-sala" id="default-sensor-temperatura-sala"><h1 class="title" data-bind="text: title, attr:{ style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{ style: title2_style}"></h1><div class="valueunit" data-bind="attr:{ style: container_style}"><h2 class="value" data-bind="html: value, attr:{ style: value_style}"></h2><p class="unit" data-bind="html: unit, attr:{ style: unit_style}"></p></div><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 1, 6)
    
    
    
    var widgets = {}
    // Initialize Widgets
    
        widgets["default-clock"] = new baseclock("default-clock", "", "dashboard", {'widget_type': 'baseclock', 'fields': {'date': '', 'time': ''}, 'static_css': {'date_style': 'color: blue;font-size: 30pt;font-weight: bold;', 'time_style': 'color: orange;font-size: 50pt;font-weight: bold;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;font-size: 200%;'}, 'static_icons': [], 'icons': [], 'css': {}, 'widget_style': 'font-size: 200%;', 'time_format': '24hr', 'date_format_country': 'pt', 'date_format_options': {'weekday': 'long', 'day': 'numeric', 'month': 'long', 'year': 'numeric'}, 'show_seconds': 0, 'time_style': 'color: orange;font-size: 50pt;font-weight: bold;', 'date_style': 'color: blue;font-size: 30pt;font-weight: bold;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-estore-cozinha"] = new baseswitch("default-estore-cozinha", "", "dashboard", {'widget_type': 'baseswitch', 'entity': 'cover.estore_cozinha', 'state_active': 'open', 'state_inactive': 'closed', 'enable': 1, 'post_service_active': {'service': 'cover/open_cover', 'entity_id': 'cover.estore_cozinha'}, 'post_service_inactive': {'service': 'cover/close_cover', 'entity_id': 'cover.estore_cozinha'}, 'fields': {'title': 'Estore Cozinha', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': 1}, 'icons': {'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds'}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'state_text': 1, 'state_map': {'open': 'Open', 'closed': 'Close'}, 'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-estore-sala"] = new baseswitch("default-estore-sala", "", "dashboard", {'widget_type': 'baseswitch', 'entity': 'cover.estore_sala', 'state_active': 'open', 'state_inactive': 'closed', 'enable': 1, 'post_service_active': {'service': 'cover/open_cover', 'entity_id': 'cover.estore_sala'}, 'post_service_inactive': {'service': 'cover/close_cover', 'entity_id': 'cover.estore_sala'}, 'fields': {'title': 'Estore Sala', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': 1}, 'icons': {'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds'}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'state_text': 1, 'state_map': {'open': 'Open', 'closed': 'Close'}, 'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-estore-mafalda"] = new baseswitch("default-estore-mafalda", "", "dashboard", {'widget_type': 'baseswitch', 'entity': 'cover.estore_mafalda', 'state_active': 'open', 'state_inactive': 'closed', 'enable': 1, 'post_service_active': {'service': 'cover/open_cover', 'entity_id': 'cover.estore_mafalda'}, 'post_service_inactive': {'service': 'cover/close_cover', 'entity_id': 'cover.estore_mafalda'}, 'fields': {'title': 'Estore Mafalda', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': 1}, 'icons': {'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds'}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'state_text': 1, 'state_map': {'open': 'Open', 'closed': 'Close'}, 'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-cover-estore-varanda-shelly"] = new baseswitch("default-cover-estore-varanda-shelly", "", "dashboard", {'widget_type': 'baseswitch', 'entity': 'cover.estore_varanda_shelly', 'state_active': 'open', 'state_inactive': 'closed', 'enable': 1, 'post_service_active': {'service': 'cover/open_cover', 'entity_id': 'cover.estore_varanda_shelly'}, 'post_service_inactive': {'service': 'cover/close_cover', 'entity_id': 'cover.estore_varanda_shelly'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds'}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-input-select-estados-de-succao"] = new baseselect("default-input-select-estados-de-succao", "", "dashboard", {'widget_type': 'baseselect', 'entity': 'input_select.estados_de_succao', 'post_service': {'service': 'input_select/select_option', 'entity_id': 'input_select.estados_de_succao'}, 'fields': {'title': '', 'title2': '', 'inputoptions': [], 'selectedoption': ''}, 'icons': [], 'css': {}, 'static_icons': {}, 'static_css': {'title_style': '', 'title2_style': '', 'select_style': '', 'selectcontainer_style': '', 'widget_style': ''}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-input-select-zonas-de-aspiracao"] = new baseselect("default-input-select-zonas-de-aspiracao", "", "dashboard", {'widget_type': 'baseselect', 'entity': 'input_select.zonas_de_aspiracao', 'post_service': {'service': 'input_select/select_option', 'entity_id': 'input_select.zonas_de_aspiracao'}, 'fields': {'title': '', 'title2': '', 'inputoptions': [], 'selectedoption': ''}, 'icons': [], 'css': {}, 'static_icons': {}, 'static_css': {'title_style': '', 'title2_style': '', 'select_style': '', 'selectcontainer_style': '', 'widget_style': ''}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-cover-estore-q-pequeno-shelly"] = new baseswitch("default-cover-estore-q-pequeno-shelly", "", "dashboard", {'widget_type': 'baseswitch', 'entity': 'cover.estore_q_pequeno_shelly', 'state_active': 'open', 'state_inactive': 'closed', 'enable': 1, 'post_service_active': {'service': 'cover/open_cover', 'entity_id': 'cover.estore_q_pequeno_shelly'}, 'post_service_inactive': {'service': 'cover/close_cover', 'entity_id': 'cover.estore_q_pequeno_shelly'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds'}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-0x680ae2fffec92973-light"] = new baselight("default-light-0x680ae2fffec92973-light", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.0x680ae2fffec92973_light', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.0x680ae2fffec92973_light'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.0x680ae2fffec92973_light'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-candeeiro-patio-1"] = new baselight("default-light-candeeiro-patio-1", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.candeeiro_patio_1', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.candeeiro_patio_1'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.candeeiro_patio_1'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-candeeiro-patio-2"] = new baselight("default-light-candeeiro-patio-2", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.candeeiro_patio_2', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.candeeiro_patio_2'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.candeeiro_patio_2'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-candeeiro-patio-3"] = new baselight("default-light-candeeiro-patio-3", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.candeeiro_patio_3', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.candeeiro_patio_3'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.candeeiro_patio_3'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-candeeiro-patio-4"] = new baselight("default-light-candeeiro-patio-4", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.candeeiro_patio_4', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.candeeiro_patio_4'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.candeeiro_patio_4'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-downlight-direito"] = new baselight("default-light-downlight-direito", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.downlight_direito', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.downlight_direito'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.downlight_direito'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-downlight-esquerdo"] = new baselight("default-light-downlight-esquerdo", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.downlight_esquerdo', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.downlight_esquerdo'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.downlight_esquerdo'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-espelho-casa-de-banho"] = new baselight("default-light-espelho-casa-de-banho", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.espelho_casa_de_banho', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.espelho_casa_de_banho'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.espelho_casa_de_banho'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-gateway-light-7811dcb38555"] = new baselight("default-light-gateway-light-7811dcb38555", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.gateway_light_7811dcb38555', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.gateway_light_7811dcb38555'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.gateway_light_7811dcb38555'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-iluminacao-coberto"] = new baselight("default-light-iluminacao-coberto", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.iluminacao_coberto', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.iluminacao_coberto'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.iluminacao_coberto'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-iluminacao-das-garagens"] = new baselight("default-light-iluminacao-das-garagens", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.iluminacao_das_garagens', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.iluminacao_das_garagens'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.iluminacao_das_garagens'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-iluminacao-do-jardim"] = new baselight("default-light-iluminacao-do-jardim", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.iluminacao_do_jardim', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.iluminacao_do_jardim'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.iluminacao_do_jardim'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-iluminacao-lateral"] = new baselight("default-light-iluminacao-lateral", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.iluminacao_lateral', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.iluminacao_lateral'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.iluminacao_lateral'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-leds-armario"] = new baselight("default-light-leds-armario", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.leds_armario', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.leds_armario'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.leds_armario'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-teto-casa-de-banho"] = new baselight("default-light-teto-casa-de-banho", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.teto_casa_de_banho', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.teto_casa_de_banho'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.teto_casa_de_banho'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-teto-da-sala"] = new baselight("default-light-teto-da-sala", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.teto_da_sala', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.teto_da_sala'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.teto_da_sala'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-teto-quarto"] = new baselight("default-light-teto-quarto", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.teto_quarto', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.teto_quarto'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.teto_quarto'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-teto-quarto-mafalda"] = new baselight("default-light-teto-quarto-mafalda", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.teto_quarto_mafalda', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.teto_quarto_mafalda'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.teto_quarto_mafalda'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-wc-pai"] = new baselight("default-light-wc-pai", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.wc_pai', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.wc_pai'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.wc_pai'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-xiaomi-philips-zhirui"] = new baselight("default-light-xiaomi-philips-zhirui", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.xiaomi_philips_zhirui', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.xiaomi_philips_zhirui'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.xiaomi_philips_zhirui'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-xiaomi-philips-zhirui-1"] = new baselight("default-light-xiaomi-philips-zhirui-1", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.xiaomi_philips_zhirui_1', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.xiaomi_philips_zhirui_1'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.xiaomi_philips_zhirui_1'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-xiaomi-philips-zhirui-2"] = new baselight("default-light-xiaomi-philips-zhirui-2", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.xiaomi_philips_zhirui_2', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.xiaomi_philips_zhirui_2'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.xiaomi_philips_zhirui_2'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-yeelight-color1-7811dc6b98cb"] = new baselight("default-light-yeelight-color1-7811dc6b98cb", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.yeelight_color1_7811dc6b98cb', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.yeelight_color1_7811dc6b98cb'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.yeelight_color1_7811dc6b98cb'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-yeelight-color1-7811dc6b9b10"] = new baselight("default-light-yeelight-color1-7811dc6b9b10", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.yeelight_color1_7811dc6b9b10', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.yeelight_color1_7811dc6b9b10'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.yeelight_color1_7811dc6b9b10'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-yeelight-color1-7811dce0fe41"] = new baselight("default-light-yeelight-color1-7811dce0fe41", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.yeelight_color1_7811dce0fe41', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.yeelight_color1_7811dce0fe41'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.yeelight_color1_7811dce0fe41'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-light-yeelight-color1-7811dce12676"] = new baselight("default-light-yeelight-color1-7811dce12676", "", "dashboard", {'widget_type': 'baselight', 'entity': 'light.yeelight_color1_7811dce12676', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.yeelight_color1_7811dce12676'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.yeelight_color1_7811dce12676'}, 'fields': {'title': '', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'fa-lightbulb-o', 'icon_off': 'fa-lightbulb-o'}, 'static_icons': {'icon_up': 'fa-plus', 'icon_down': 'fa-minus'}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #888;', 'unit_style': 'color: #888;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;'}, 'css': {'icon_style_active': 'color: #ffff00;', 'icon_style_inactive': 'color: antiquewhite;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    
        widgets["default-sensor-temperatura-sala"] = new basedisplay("default-sensor-temperatura-sala", "", "dashboard", {'widget_type': 'basedisplay', 'entity': 'sensor.temperatura_sala', 'entity_to_sub_entity_attribute': '', 'sub_entity': '', 'sub_entity_to_entity_attribute': '', 'fields': {'title': '', 'title2': '', 'value': '', 'unit': '', 'state_text': ''}, 'static_css': {'title_style': 'color: #fff;font-weight: 400;', 'title2_style': 'color: #fff;font-weight: 400;', 'state_text_style': '', 'widget_style': 'background-color: rgba(68,68,68,0.7);color: #00aaff;', 'container_style': ''}, 'css': {'value_style': 'font-size: 250%;', 'text_style': 'font-size: 100%;', 'unit_style': 'font-size: 100%;'}, 'icons': [], 'static_icons': [], 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 1, 'namespace': 'default'})
    

    // Setup click handler to cancel timeout navigations

    $( ".gridster" ).click(function(){
        clearTimeout(myTimeout);
        if (myTimeoutSticky) {
            myTimeout = setTimeout(function() { navigate(myTimeoutUrl); }, myTimeoutDelay);
        }
    });

    // Set up timeout

    var myTimeout;
    var myTimeoutUrl;
    var myTimeoutDelay;
    var myTimeoutSticky = 0;

    if (location.search != "")
    {
        var query = location.search.substr(1);
        var result = {};
        query.split("&").forEach(function(part) {
        var item = part.split("=");
        result[item[0]] = decodeURIComponent(item[1]);
        });

        if ("timeout" in result && "return" in result)
        {
            url = result.return
            argcount = 0
            for (arg in result)
            {
                if (arg != "timeout" && arg != "return" && arg != "sticky")
                {
                    if (argcount == 0)
                    {
                        url += "?";
                    }
                    else
                    {
                        url += "?";
                    }
                    argcount ++;
                    url += arg + "=" + result[arg]
                }
            }
            if ("sticky" in result)
            {
                myTimeoutSticky = (result.sticky == "1");
            }
            myTimeoutUrl = url;
            myTimeoutDelay = result.timeout * 1000;
            myTimeout = setTimeout(function() { navigate(url); }, result.timeout * 1000);
        }
    }

    // Start listening for HA Events

    
    if (location.protocol == 'https:')
    {
        wsprot = "wss:"
    }
    else
    {
        wsprot = "ws:"
    }
    var stream_url = wsprot + '//' + location.host + '/stream'
    

    ha_status(stream_url, "Casa Inteligente", widgets, "ws");

});