$(function(){ //DOM Ready

    function navigate(url)
    {
        window.location.href = url;
    }

    $(document).attr("title", "Rádio");
    content_width = (120 + 5) * 10 + 5
    $('.gridster').width(content_width)
    $(".gridster ul").gridster({
        widget_margins: [5, 5],
        widget_base_dimensions: [120, 120],
        avoid_overlapped_widgets: true,
        max_rows: 15,
        max_size_x: 10,
        shift_widgets_up: false
    }).data('gridster').disable();
    
    // Add Widgets

    var gridster = $(".gridster ul").gridster().data('gridster');
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-radio-comercial-sala" id="default-script-radio-comercial-sala"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 1, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-rfm-sala" id="default-script-rfm-sala"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 2, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-m80-sala" id="default-script-m80-sala"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 3, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-vodafone-sala" id="default-script-vodafone-sala"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 4, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-radio-stop-sala" id="default-script-radio-stop-sala"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 5, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseinputnumber-default-input-number-sala-volume" id="default-input-number-sala-volume"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><div class="slidercontainer" data-bind="attr:{style: slidercontainer_style}"><input type="range" data-bind="attr: {min: MinValue, max: MaxValue, step: StepValue, style: slider_style}, value: SliderValue" ></div><p class="minval" data-bind="text: minValue, attr:{style: minvalue_style}"></p><p class="value" data-bind="text: sliderValue, attr:{style: value_style}"></p><p class="maxval" data-bind="text: maxValue, attr:{style: maxvalue_style}"></p></div></li>', 2, 1, 6, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-radio-comercial-cozinha" id="default-script-radio-comercial-cozinha"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 1, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-rfm-cozinha" id="default-script-rfm-cozinha"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 2, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-m80-cozinha" id="default-script-m80-cozinha"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 3, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-vodafone-cozinha" id="default-script-vodafone-cozinha"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 4, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-radio-stop-cozinha" id="default-script-radio-stop-cozinha"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 5, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseinputnumber-default-input-number-cozinha-volume" id="default-input-number-cozinha-volume"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><div class="slidercontainer" data-bind="attr:{style: slidercontainer_style}"><input type="range" data-bind="attr: {min: MinValue, max: MaxValue, step: StepValue, style: slider_style}, value: SliderValue" ></div><p class="minval" data-bind="text: minValue, attr:{style: minvalue_style}"></p><p class="value" data-bind="text: sliderValue, attr:{style: value_style}"></p><p class="maxval" data-bind="text: maxValue, attr:{style: maxvalue_style}"></p></div></li>', 2, 1, 6, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-radio-comercial-ambiente" id="default-script-radio-comercial-ambiente"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 1, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-rfm-ambiente" id="default-script-rfm-ambiente"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 2, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-m80-ambiente" id="default-script-m80-ambiente"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 3, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-vodafone-ambiente" id="default-script-vodafone-ambiente"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 4, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-script-radio-stop-som-ambiente" id="default-script-radio-stop-som-ambiente"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 5, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseinputnumber-default-input-number-ambiente-volume" id="default-input-number-ambiente-volume"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><div class="slidercontainer" data-bind="attr:{style: slidercontainer_style}"><input type="range" data-bind="attr: {min: MinValue, max: MaxValue, step: StepValue, style: slider_style}, value: SliderValue" ></div><p class="minval" data-bind="text: minValue, attr:{style: minvalue_style}"></p><p class="value" data-bind="text: sliderValue, attr:{style: value_style}"></p><p class="maxval" data-bind="text: maxValue, attr:{style: maxvalue_style}"></p></div></li>', 2, 1, 6, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basemedia-default-media-player-spotify-bruno-melo" id="default-media-player-spotify-bruno-melo"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="artist" data-bind="text: artist, attr:{style: artist_style}"></h1><h1 class="media_title" data-bind="text: media_title, attr:{style: media_title_style}"></h1><h1 class="album" data-bind="text: album, attr:{style: album_style}"></h1><h2 id="previous" class="previous" data-bind="attr:{style: previous_icon_style}"><i data-bind="attr: {class: previous_icon}"></i></h2><h2 id="play" class="play" data-bind="attr:{style: play_icon_style}"><i data-bind="attr: {class: play_icon}"></i></h2><h2 id="next" class="next" data-bind="attr:{style: next_icon_style}"><i data-bind="attr: {class: next_icon}"></i></h2><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="attr:{style: units_style}">%</p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 2, 2, 5, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basejavascript-default-load-main-panel" id="default-load-main-panel"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2></div></li>', 1, 1, 8, 6)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basejavascript-default-load-secundario-panel" id="default-load-secundario-panel"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2></div></li>', 1, 1, 9, 6)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basejavascript-default-load-aspirador-panel" id="default-load-aspirador-panel"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2></div></li>', 1, 1, 10, 6)
    
    
    
    var widgets = {}
    // Initialize Widgets
    
        widgets["default-script-radio-comercial-sala"] = new baseswitch("default-script-radio-comercial-sala", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.radio_comercial_sala', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.radio_comercial_sala'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.radio_comercial_sala'}, 'fields': {'title': 'Comercial Sala', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/Comercial.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/Comercial.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-rfm-sala"] = new baseswitch("default-script-rfm-sala", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.rfm_sala', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.rfm_sala'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.rfm_sala'}, 'fields': {'title': 'RFM Sala', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/rfm.png);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/rfm.png);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-m80-sala"] = new baseswitch("default-script-m80-sala", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.m80_sala', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.m80_sala'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.m80_sala'}, 'fields': {'title': 'M80 Sala', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/m80.png);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/m80.png);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-vodafone-sala"] = new baseswitch("default-script-vodafone-sala", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.vodafone_sala', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.vodafone_sala'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.vodafone_sala'}, 'fields': {'title': 'Vodafone Sala', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/vodafone.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/vodafone.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-radio-stop-sala"] = new baseswitch("default-script-radio-stop-sala", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.radio_stop_sala', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.radio_stop_sala'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.radio_stop_sala'}, 'fields': {'title': 'Parar Rádio Sala', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: black;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/stop.png);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: black;', 'widget_style': 'background-image: url(/custom_css/icon/stop.png);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-input-number-sala-volume"] = new baseinputnumber("default-input-number-sala-volume", "", "blur_light", {'widget_type': 'baseinputnumber', 'entity': 'input_number.sala_volume', 'post_service': {'service': 'input_number/set_value', 'entity_id': 'input_number.sala_volume'}, 'fields': {'title': '', 'title2': '', 'SliderValue': '', 'MinValue': '', 'MaxValue': '', 'sliderValue': '', 'minValue': '', 'maxValue': '', 'StepValue': ''}, 'icons': [], 'css': {}, 'static_icons': [], 'static_css': {'title_style': '', 'title2_style': '', 'minvalue_style': '', 'maxvalue_style': '', 'value_style': '', 'slider_style': '', 'slidercontainer_style': '', 'widget_style': ''}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-radio-comercial-cozinha"] = new baseswitch("default-script-radio-comercial-cozinha", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.radio_comercial_cozinha', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.radio_comercial_cozinha'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.radio_comercial_cozinha'}, 'fields': {'title': 'Comercial cozinha', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/Comercial.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/Comercial.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-rfm-cozinha"] = new baseswitch("default-script-rfm-cozinha", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.rfm_cozinha', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.rfm_cozinha'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.rfm_cozinha'}, 'fields': {'title': 'RFM cozinha', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/rfm.png);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/rfm.png);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-m80-cozinha"] = new baseswitch("default-script-m80-cozinha", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.m80_cozinha', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.m80_cozinha'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.m80_cozinha'}, 'fields': {'title': 'M80 cozinha', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/m80.png);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/m80.png);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-vodafone-cozinha"] = new baseswitch("default-script-vodafone-cozinha", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.vodafone_cozinha', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.vodafone_cozinha'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.vodafone_cozinha'}, 'fields': {'title': 'Vodafone cozinha', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/vodafone.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/vodafone.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-radio-stop-cozinha"] = new baseswitch("default-script-radio-stop-cozinha", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.radio_stop_cozinha', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.radio_stop_cozinha'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.radio_stop_cozinha'}, 'fields': {'title': 'Parar Rádio cozinha', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: black;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/stop.png);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: black;', 'widget_style': 'background-image: url(/custom_css/icon/stop.png);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-input-number-cozinha-volume"] = new baseinputnumber("default-input-number-cozinha-volume", "", "blur_light", {'widget_type': 'baseinputnumber', 'entity': 'input_number.cozinha_volume', 'post_service': {'service': 'input_number/set_value', 'entity_id': 'input_number.cozinha_volume'}, 'fields': {'title': '', 'title2': '', 'SliderValue': '', 'MinValue': '', 'MaxValue': '', 'sliderValue': '', 'minValue': '', 'maxValue': '', 'StepValue': ''}, 'icons': [], 'css': {}, 'static_icons': [], 'static_css': {'title_style': '', 'title2_style': '', 'minvalue_style': '', 'maxvalue_style': '', 'value_style': '', 'slider_style': '', 'slidercontainer_style': '', 'widget_style': ''}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-radio-comercial-ambiente"] = new baseswitch("default-script-radio-comercial-ambiente", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.radio_comercial_ambiente', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.radio_comercial_ambiente'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.radio_comercial_ambiente'}, 'fields': {'title': 'Comercial casa', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/Comercial.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/Comercial.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-rfm-ambiente"] = new baseswitch("default-script-rfm-ambiente", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.rfm_ambiente', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.rfm_ambiente'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.rfm_ambiente'}, 'fields': {'title': 'RFM casa', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/rfm.png);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/rfm.png);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-m80-ambiente"] = new baseswitch("default-script-m80-ambiente", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.m80_ambiente', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.m80_ambiente'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.m80_ambiente'}, 'fields': {'title': 'M80 casa', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/m80.png);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/m80.png);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-vodafone-ambiente"] = new baseswitch("default-script-vodafone-ambiente", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.vodafone_ambiente', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.vodafone_ambiente'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.vodafone_ambiente'}, 'fields': {'title': 'Vodafone casa', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/vodafone.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'widget_style': 'background-image: url(/custom_css/icon/vodafone.jpg);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-script-radio-stop-som-ambiente"] = new baseswitch("default-script-radio-stop-som-ambiente", "", "blur_light", {'widget_type': 'baseswitch', 'entity': 'script.radio_stop_som_ambiente', 'state_inactive': 'off', 'state_active': 'on', 'enable': 1, 'momentary': 1000, 'ignore_state': 1, 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'script.radio_stop_som_ambiente'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'script.radio_stop_som_ambiente'}, 'fields': {'title': 'Parar Rádio casa', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': ''}, 'icons': {'icon_on': '', 'icon_off': ''}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: black;'}, 'static_css': {'title_style': 'color: white;', 'title2_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);background-image: url(/custom_css/icon/stop.png);background-size: 40%;background-position:center;background-repeat: no-repeat;'}, 'title_style': 'color: white;', 'icon_on': '', 'icon_off': '', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: black;', 'widget_style': 'background-image: url(/custom_css/icon/stop.png);background-size: 40%;background-position:center;background-repeat: no-repeat;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-input-number-ambiente-volume"] = new baseinputnumber("default-input-number-ambiente-volume", "", "blur_light", {'widget_type': 'baseinputnumber', 'entity': 'input_number.ambiente_volume', 'post_service': {'service': 'input_number/set_value', 'entity_id': 'input_number.ambiente_volume'}, 'fields': {'title': '', 'title2': '', 'SliderValue': '', 'MinValue': '', 'MaxValue': '', 'sliderValue': '', 'minValue': '', 'maxValue': '', 'StepValue': ''}, 'icons': [], 'css': {}, 'static_icons': [], 'static_css': {'title_style': '', 'title2_style': '', 'minvalue_style': '', 'maxvalue_style': '', 'value_style': '', 'slider_style': '', 'slidercontainer_style': '', 'widget_style': ''}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-media-player-spotify-bruno-melo"] = new basemedia("default-media-player-spotify-bruno-melo", "", "blur_light", {'widget_type': 'basemedia', 'entity': 'media_player.spotify_bruno_melo', 'post_service_next': {'service': 'media_player/media_next_track', 'entity_id': 'media_player.spotify_bruno_melo'}, 'post_service_previous': {'service': 'media_player/media_previous_track', 'entity_id': 'media_player.spotify_bruno_melo'}, 'post_service_play_pause': {'service': 'media_player/media_play_pause', 'entity_id': 'media_player.spotify_bruno_melo'}, 'post_service_pause': {'service': 'media_player/media_pause', 'entity_id': 'media_player.spotify_bruno_melo'}, 'post_service_stop': {'service': 'media_player/media_stop', 'entity_id': 'media_player.spotify_bruno_melo'}, 'post_service_level': {'service': 'media_player/volume_set', 'entity_id': 'media_player.spotify_bruno_melo'}, 'fields': {'title': 'Spotify', 'artist': '', 'media_title': '', 'album': '', 'play_icon_style': '', 'pause_icon_style': '', 'previous_icon_style': '', 'next_icon_style': '', 'state_text': '', 'level': ''}, 'icons': {'play_icon': 'fas-play', 'pause_icon': 'fas-pause'}, 'static_icons': {'previous_icon': 'fas-step-backward', 'next_icon': 'fas-step-forward', 'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'previous_icon_style': 'color: #888;', 'next_icon_style': 'color: #888;', 'title_style': 'color: #646464;font-weight: 400;', 'artist_style': 'color: #646464;font-weight: 400;', 'album_style': 'color: #646464;font-weight: 400;', 'media_title_style': 'color: #646464;font-weight: 400;', 'state_text_style': 'color: #646464;', 'level_style': 'color: #646464;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);', 'units_style': 'color: #646464;'}, 'css': {'icon_style_active': 'color: #aaff00;', 'icon_style_inactive': 'color: #888;'}, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-load-main-panel"] = new basejavascript("default-load-main-panel", "", "blur_light", {'widget_type': 'basejavascript', 'fields': {'title': 'Painel Principal', 'title2': '', 'icon': '', 'icon_style': ''}, 'icons': {'icon_active': 'fa-spinner fa-spin', 'icon_inactive': 'mdi-home-assistant'}, 'static_css': {'title_style': 'color: Black;font-weight: 400;', 'title2_style': 'color: #646464;font-weight: 400;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);'}, 'css': {'icon_active_style': 'color: #646464;', 'icon_inactive_style': 'color: blue;'}, 'static_icons': [], 'icon_inactive': 'mdi-home-assistant', 'dashboard': 'ha_dashboard', 'title_style': 'color: Black;', 'icon_inactive_style': 'color: blue;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-load-secundario-panel"] = new basejavascript("default-load-secundario-panel", "", "blur_light", {'widget_type': 'basejavascript', 'fields': {'title': 'Painel Secundário', 'title2': '', 'icon': '', 'icon_style': ''}, 'icons': {'icon_active': 'fa-spinner fa-spin', 'icon_inactive': 'mdi-home-floor-2'}, 'static_css': {'title_style': 'color: Black;font-weight: 400;', 'title2_style': 'color: #646464;font-weight: 400;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);'}, 'css': {'icon_active_style': 'color: #646464;', 'icon_inactive_style': 'color: blue;'}, 'static_icons': [], 'icon_inactive': 'mdi-home-floor-2', 'dashboard': 'segundo_painel', 'title_style': 'color: Black;', 'icon_inactive_style': 'color: blue;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-load-aspirador-panel"] = new basejavascript("default-load-aspirador-panel", "", "blur_light", {'widget_type': 'basejavascript', 'fields': {'title': 'RoboRock S50', 'title2': '', 'icon': '', 'icon_style': ''}, 'icons': {'icon_active': 'fa-spinner fa-spin', 'icon_inactive': 'mdi-robot-vacuum'}, 'static_css': {'title_style': 'color: Black;font-weight: 400;', 'title2_style': 'color: #646464;font-weight: 400;', 'widget_style': 'backdrop-filter: blur(30px);background-color: rgba(255, 255, 255, 0.5);'}, 'css': {'icon_active_style': 'color: #646464;', 'icon_inactive_style': 'color: black;'}, 'static_icons': [], 'icon_inactive': 'mdi-robot-vacuum', 'dashboard': 'aspirador', 'title_style': 'color: Black;', 'icon_inactive_style': 'color: black;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    

    // Setup click handler to cancel timeout navigations

    $( ".gridster" ).click(function(){
        clearTimeout(myTimeout);
        if (myTimeoutSticky) {
            myTimeout = setTimeout(function() { navigate(myTimeoutUrl); }, myTimeoutDelay);
        }
    });

    // Set up timeout

    var myTimeout;
    var myTimeoutUrl;
    var myTimeoutDelay;
    var myTimeoutSticky = 0;

    if (location.search != "")
    {
        var query = location.search.substr(1);
        var result = {};
        query.split("&").forEach(function(part) {
        var item = part.split("=");
        result[item[0]] = decodeURIComponent(item[1]);
        });

        if ("timeout" in result && "return" in result)
        {
            url = result.return
            argcount = 0
            for (arg in result)
            {
                if (arg != "timeout" && arg != "return" && arg != "sticky")
                {
                    if (argcount == 0)
                    {
                        url += "?";
                    }
                    else
                    {
                        url += "?";
                    }
                    argcount ++;
                    url += arg + "=" + result[arg]
                }
            }
            if ("sticky" in result)
            {
                myTimeoutSticky = (result.sticky == "1");
            }
            myTimeoutUrl = url;
            myTimeoutDelay = result.timeout * 1000;
            myTimeout = setTimeout(function() { navigate(url); }, result.timeout * 1000);
        }
    }

    // Start listening for HA Events

    
    if (location.protocol == 'https:')
    {
        wsprot = "wss:"
    }
    else
    {
        wsprot = "ws:"
    }
    var stream_url = wsprot + '//' + location.host + '/stream'
    

    ha_status(stream_url, "Rádio", widgets, "ws");

});