$(function(){ //DOM Ready

    function navigate(url)
    {
        window.location.href = url;
    }

    $(document).attr("title", "Casa Inteligente");
    content_width = (120 + 5) * 10 + 5
    $('.gridster').width(content_width)
    $(".gridster ul").gridster({
        widget_margins: [5, 5],
        widget_base_dimensions: [120, 120],
        avoid_overlapped_widgets: true,
        max_rows: 15,
        max_size_x: 10,
        shift_widgets_up: false
    }).data('gridster').disable();
    
    // Add Widgets

    var gridster = $(".gridster ul").gridster().data('gridster');
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseclock-default-clock" id="default-clock"><h1 class="date"data-bind="text: date, attr: {style: date_style}"></h1><h2 class="time" data-bind="text: time, attr: {style: time_style}"></h2></div></li>', 4, 2, 1, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-estore-cozinha" id="default-estore-cozinha"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 5, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-estore-sala" id="default-estore-sala"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 6, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-estore-mafalda" id="default-estore-mafalda"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 7, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-estore-varanda-shelly" id="default-estore-varanda-shelly"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 8, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseswitch-default-estore-q-pequeno-shelly" id="default-estore-q-pequeno-shelly"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><h1 class="state_text" data-bind="text: state_text, attr: {style: state_text_style}"></h1></div></li>', 1, 1, 9, 1)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baseinputnumber-default-input-number-estoresala" id="default-input-number-estoresala"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><div class="slidercontainer" data-bind="attr:{style: slidercontainer_style}"><input type="range" data-bind="attr: {min: MinValue, max: MaxValue, step: StepValue, style: slider_style}, value: SliderValue" ></div><p class="minval" data-bind="text: minValue, attr:{style: minvalue_style}"></p><p class="value" data-bind="text: sliderValue, attr:{style: value_style}"></p><p class="maxval" data-bind="text: maxValue, attr:{style: maxvalue_style}"></p></div></li>', 1, 1, 6, 2)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-0x680ae2fffec92973-light" id="default-0x680ae2fffec92973-light"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 1, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-candeeiro-patio-1" id="default-candeeiro-patio-1"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 2, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-candeeiro-patio-2" id="default-candeeiro-patio-2"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 3, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-candeeiro-patio-3" id="default-candeeiro-patio-3"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 4, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-candeeiro-patio-4" id="default-candeeiro-patio-4"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 5, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-downlight-direito" id="default-downlight-direito"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 6, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-downlight-esquerdo" id="default-downlight-esquerdo"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 7, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-espelho-casa-de-banho" id="default-espelho-casa-de-banho"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 8, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-teto-casa-de-banho" id="default-teto-casa-de-banho"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 9, 3)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-iluminacao-coberto" id="default-iluminacao-coberto"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 1, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-iluminacao-das-garagens" id="default-iluminacao-das-garagens"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 2, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-iluminacao-do-jardim" id="default-iluminacao-do-jardim"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 3, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-iluminacao-lateral" id="default-iluminacao-lateral"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 4, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-leds-armario" id="default-leds-armario"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 5, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-gateway-light-7811dcb38555" id="default-gateway-light-7811dcb38555"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 6, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-teto-da-sala" id="default-teto-da-sala"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 7, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-teto-quarto" id="default-teto-quarto"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 8, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-teto-quarto-mafalda" id="default-teto-quarto-mafalda"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 9, 4)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-wc-pai" id="default-wc-pai"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 1, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-xiaomi-philips-zhirui" id="default-xiaomi-philips-zhirui"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 2, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-xiaomi-philips-zhirui-1" id="default-xiaomi-philips-zhirui-1"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 3, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-xiaomi-philips-zhirui-2" id="default-xiaomi-philips-zhirui-2"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 4, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-yeelight-color1-7811dc6b98cb" id="default-yeelight-color1-7811dc6b98cb"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 5, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-yeelight-color1-7811dc6b9b10" id="default-yeelight-color1-7811dc6b9b10"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 6, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-yeelight-color1-7811dce0fe41" id="default-yeelight-color1-7811dce0fe41"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 7, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-yeelight-color1-7811dce12676" id="default-yeelight-color1-7811dce12676"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 8, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-baselight-default-leds-armario-sala" id="default-leds-armario-sala"><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2><span class="toggle-area" id="switch"></span><p class="state_text" data-bind="text: state_text, attr:{style: state_text_style}"></p><div class="levelunit"><p class="level" data-bind="text: level, attr:{style: level_style}"></p><p class="unit" data-bind="html: units, attr:{style: unit_style}"></p></div><p class="secondary-icon minus"><i data-bind="attr: {class: icon_down, style: level_down_style}" id="level-down"></i></p><p class="secondary-icon plus"><i data-bind="attr: {class: icon_up, style: level_up_style}" id="level-up"></i></p></div></li>', 1, 1, 9, 5)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basejavascript-default-load-secundario-panel" id="default-load-secundario-panel"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2></div></li>', 1, 1, 8, 6)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basejavascript-default-load-radio-panel" id="default-load-radio-panel"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2></div></li>', 1, 1, 9, 6)
    
        gridster.add_widget('<li><div data-bind="attr: {style: widget_style}" class="widget widget-basejavascript-default-load-aspirador-panel" id="default-load-aspirador-panel"><span class="toggle-area" id="switch"></span><h1 class="title" data-bind="text: title, attr:{style: title_style}"></h1><h1 class="title2" data-bind="text: title2, attr:{style: title2_style}"></h1><h2 class="icon" data-bind="attr:{style: icon_style}"><i data-bind="attr: {class: icon}"></i></h2></div></li>', 1, 1, 10, 6)
    
    
    
    var widgets = {}
    // Initialize Widgets
    
        widgets["default-clock"] = new baseclock("default-clock", "", "default", {'widget_type': 'baseclock', 'fields': {'date': '', 'time': ''}, 'static_css': {'date_style': 'color: white;font-size: 20pt;font-weight: bold;', 'time_style': 'color: black;font-size: 70pt;font-weight: bold;font-family: Courier New;', 'widget_style': 'background-color: #444;font-size: 200%;'}, 'static_icons': [], 'icons': [], 'css': {}, 'widget_style': 'font-size: 200%;', 'time_format': '24hr', 'date_format_country': 'pt', 'date_format_options': {'weekday': 'long', 'day': 'numeric', 'month': 'long', 'year': 'numeric'}, 'show_seconds': 1, 'time_style': 'color: black;font-size: 70pt;font-weight: bold;font-family: Courier New;', 'date_style': 'color: white;font-size: 20pt;font-weight: bold;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-estore-cozinha"] = new baseswitch("default-estore-cozinha", "", "default", {'widget_type': 'baseswitch', 'entity': 'cover.estore_cozinha', 'state_active': 'open', 'state_inactive': 'closed', 'enable': 1, 'post_service_active': {'service': 'cover/open_cover', 'entity_id': 'cover.estore_cozinha'}, 'post_service_inactive': {'service': 'cover/close_cover', 'entity_id': 'cover.estore_cozinha'}, 'fields': {'title': 'Estore Cozinha', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': 1}, 'icons': {'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds'}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'widget_style': 'background-color: #444;'}, 'state_text': 1, 'state_map': {'open': 'Aberto', 'closed': 'Fechado'}, 'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-estore-sala"] = new baseswitch("default-estore-sala", "", "default", {'widget_type': 'baseswitch', 'entity': 'cover.estore_sala', 'state_active': 'open', 'state_inactive': 'closed', 'enable': 1, 'post_service_active': {'service': 'cover/open_cover', 'entity_id': 'cover.estore_sala'}, 'post_service_inactive': {'service': 'cover/close_cover', 'entity_id': 'cover.estore_sala'}, 'fields': {'title': 'Estore Sala', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': 1}, 'icons': {'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds'}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'widget_style': 'background-color: #444;'}, 'state_text': 1, 'state_map': {'open': 'Aberto', 'closed': 'Fechado'}, 'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-estore-mafalda"] = new baseswitch("default-estore-mafalda", "", "default", {'widget_type': 'baseswitch', 'entity': 'cover.estore_mafalda', 'state_active': 'open', 'state_inactive': 'closed', 'enable': 1, 'post_service_active': {'service': 'cover/open_cover', 'entity_id': 'cover.estore_mafalda'}, 'post_service_inactive': {'service': 'cover/close_cover', 'entity_id': 'cover.estore_mafalda'}, 'fields': {'title': 'Estore Mafalda', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': 1}, 'icons': {'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds'}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'widget_style': 'background-color: #444;'}, 'state_text': 1, 'state_map': {'open': 'Aberto', 'closed': 'Fechado'}, 'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-estore-varanda-shelly"] = new baseswitch("default-estore-varanda-shelly", "", "default", {'widget_type': 'baseswitch', 'entity': 'cover.estore_varanda_shelly', 'state_active': 'open', 'state_inactive': 'closed', 'enable': 1, 'post_service_active': {'service': 'cover/open_cover', 'entity_id': 'cover.estore_varanda_shelly'}, 'post_service_inactive': {'service': 'cover/close_cover', 'entity_id': 'cover.estore_varanda_shelly'}, 'fields': {'title': 'Estore Varanda', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': 1}, 'icons': {'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds'}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'widget_style': 'background-color: #444;'}, 'state_text': 1, 'state_map': {'open': 'Aberto', 'closed': 'Fechado'}, 'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-estore-q-pequeno-shelly"] = new baseswitch("default-estore-q-pequeno-shelly", "", "default", {'widget_type': 'baseswitch', 'entity': 'cover.estore_q_pequeno_shelly', 'state_active': 'open', 'state_inactive': 'closed', 'enable': 1, 'post_service_active': {'service': 'cover/open_cover', 'entity_id': 'cover.estore_q_pequeno_shelly'}, 'post_service_inactive': {'service': 'cover/close_cover', 'entity_id': 'cover.estore_q_pequeno_shelly'}, 'fields': {'title': 'Estore Q. Pequeno', 'title2': '', 'icon': '', 'icon_style': '', 'state_text': 1}, 'icons': {'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds'}, 'static_icons': [], 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'widget_style': 'background-color: #444;'}, 'state_text': 1, 'state_map': {'open': 'Aberto', 'closed': 'Fechado'}, 'icon_on': 'mdi-blinds-open', 'icon_off': 'mdi-blinds', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-input-number-estoresala"] = new baseinputnumber("default-input-number-estoresala", "", "default", {'widget_type': 'baseinputnumber', 'entity': 'input_number.estoresala', 'post_service': {'service': 'input_number/set_value', 'entity_id': 'input_number.estoresala'}, 'fields': {'title': '', 'title2': '', 'SliderValue': '', 'MinValue': '', 'MaxValue': '', 'sliderValue': '', 'minValue': '', 'maxValue': '', 'StepValue': ''}, 'icons': [], 'css': {}, 'static_icons': [], 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'minvalue_style': 'color: #fff;', 'maxvalue_style': 'color: #fff;', 'value_style': 'color: #fff;', 'slider_style': '-webkit-appearance: none;', 'slidercontainer_style': '', 'widget_style': 'background-color: #444;'}, 'title_is_friendly_name': 1, 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-0x680ae2fffec92973-light"] = new baselight("default-0x680ae2fffec92973-light", "", "default", {'widget_type': 'baselight', 'entity': 'light.0x680ae2fffec92973_light', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.0x680ae2fffec92973_light'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.0x680ae2fffec92973_light'}, 'fields': {'title': 'Aplique Despensa', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-lightbulb', 'icon_off': 'mdi-lightbulb'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-lightbulb', 'icon_off': 'mdi-lightbulb', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-candeeiro-patio-1"] = new baselight("default-candeeiro-patio-1", "", "default", {'widget_type': 'baselight', 'entity': 'light.candeeiro_patio_1', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.candeeiro_patio_1'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.candeeiro_patio_1'}, 'fields': {'title': 'Pátio 1', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-candeeiro-patio-2"] = new baselight("default-candeeiro-patio-2", "", "default", {'widget_type': 'baselight', 'entity': 'light.candeeiro_patio_2', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.candeeiro_patio_2'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.candeeiro_patio_2'}, 'fields': {'title': 'Pátio 2', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-candeeiro-patio-3"] = new baselight("default-candeeiro-patio-3", "", "default", {'widget_type': 'baselight', 'entity': 'light.candeeiro_patio_3', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.candeeiro_patio_3'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.candeeiro_patio_3'}, 'fields': {'title': 'Pátio 3', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-candeeiro-patio-4"] = new baselight("default-candeeiro-patio-4", "", "default", {'widget_type': 'baselight', 'entity': 'light.candeeiro_patio_4', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.candeeiro_patio_4'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.candeeiro_patio_4'}, 'fields': {'title': 'Pátio 4', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-downlight-direito"] = new baselight("default-downlight-direito", "", "default", {'widget_type': 'baselight', 'entity': 'light.downlight_direito', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.downlight_direito'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.downlight_direito'}, 'fields': {'title': 'Escritório Direita', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-downlight-esquerdo"] = new baselight("default-downlight-esquerdo", "", "default", {'widget_type': 'baselight', 'entity': 'light.downlight_esquerdo', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.downlight_esquerdo'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.downlight_esquerdo'}, 'fields': {'title': 'Escritório Esquerdo', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-espelho-casa-de-banho"] = new baselight("default-espelho-casa-de-banho", "", "default", {'widget_type': 'baselight', 'entity': 'light.espelho_casa_de_banho', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.espelho_casa_de_banho'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.espelho_casa_de_banho'}, 'fields': {'title': 'WC Espelho', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-lightbulb-on', 'icon_off': 'mdi-lightbulb'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-lightbulb-on', 'icon_off': 'mdi-lightbulb', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-teto-casa-de-banho"] = new baselight("default-teto-casa-de-banho", "", "default", {'widget_type': 'baselight', 'entity': 'light.teto_casa_de_banho', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.teto_casa_de_banho'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.teto_casa_de_banho'}, 'fields': {'title': 'WC Tecto', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-iluminacao-coberto"] = new baselight("default-iluminacao-coberto", "", "default", {'widget_type': 'baselight', 'entity': 'light.iluminacao_coberto', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.iluminacao_coberto'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.iluminacao_coberto'}, 'fields': {'title': 'Coberto', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-iluminacao-das-garagens"] = new baselight("default-iluminacao-das-garagens", "", "default", {'widget_type': 'baselight', 'entity': 'light.iluminacao_das_garagens', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.iluminacao_das_garagens'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.iluminacao_das_garagens'}, 'fields': {'title': 'Garagens', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-iluminacao-do-jardim"] = new baselight("default-iluminacao-do-jardim", "", "default", {'widget_type': 'baselight', 'entity': 'light.iluminacao_do_jardim', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.iluminacao_do_jardim'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.iluminacao_do_jardim'}, 'fields': {'title': 'Iluminação do jardim', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-iluminacao-lateral"] = new baselight("default-iluminacao-lateral", "", "default", {'widget_type': 'baselight', 'entity': 'light.iluminacao_lateral', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.iluminacao_lateral'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.iluminacao_lateral'}, 'fields': {'title': 'Passagem do Jardim', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-leds-armario"] = new baselight("default-leds-armario", "", "default", {'widget_type': 'baselight', 'entity': 'light.leds_armario', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.leds_armario'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.leds_armario'}, 'fields': {'title': 'Iluminação da despensa', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-led-strip', 'icon_off': 'mdi-led-strip'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-led-strip', 'icon_off': 'mdi-led-strip', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-gateway-light-7811dcb38555"] = new baselight("default-gateway-light-7811dcb38555", "", "default", {'widget_type': 'baselight', 'entity': 'light.gateway_light_7811dcb38555', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.gateway_light_7811dcb38555'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.gateway_light_7811dcb38555'}, 'fields': {'title': 'Iluminação gateway', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-led-strip', 'icon_off': 'mdi-led-strip'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-led-strip', 'icon_off': 'mdi-led-strip', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-teto-da-sala"] = new baselight("default-teto-da-sala", "", "default", {'widget_type': 'baselight', 'entity': 'light.teto_da_sala', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.teto_da_sala'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.teto_da_sala'}, 'fields': {'title': 'Tecto da sala', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-teto-quarto"] = new baselight("default-teto-quarto", "", "default", {'widget_type': 'baselight', 'entity': 'light.teto_quarto', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.teto_quarto'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.teto_quarto'}, 'fields': {'title': 'Tecto do quarto', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-teto-quarto-mafalda"] = new baselight("default-teto-quarto-mafalda", "", "default", {'widget_type': 'baselight', 'entity': 'light.teto_quarto_mafalda', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.teto_quarto_mafalda'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.teto_quarto_mafalda'}, 'fields': {'title': 'Tecto quarto Mafalda', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-wc-pai"] = new baselight("default-wc-pai", "", "default", {'widget_type': 'baselight', 'entity': 'light.wc_pai', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.wc_pai'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.wc_pai'}, 'fields': {'title': 'Tecto WC pai', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-wall-sconce-flat', 'icon_off': 'mdi-wall-sconce-flat', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-xiaomi-philips-zhirui"] = new baselight("default-xiaomi-philips-zhirui", "", "default", {'widget_type': 'baselight', 'entity': 'light.xiaomi_philips_zhirui', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.xiaomi_philips_zhirui'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.xiaomi_philips_zhirui'}, 'fields': {'title': 'Downlight cozinha entrada', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-track-light', 'icon_off': 'mdi-track-light'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-track-light', 'icon_off': 'mdi-track-light', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-xiaomi-philips-zhirui-1"] = new baselight("default-xiaomi-philips-zhirui-1", "", "default", {'widget_type': 'baselight', 'entity': 'light.xiaomi_philips_zhirui_1', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.xiaomi_philips_zhirui_1'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.xiaomi_philips_zhirui_1'}, 'fields': {'title': 'Downlight cozinha meio', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-track-light', 'icon_off': 'mdi-track-light'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-track-light', 'icon_off': 'mdi-track-light', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-xiaomi-philips-zhirui-2"] = new baselight("default-xiaomi-philips-zhirui-2", "", "default", {'widget_type': 'baselight', 'entity': 'light.xiaomi_philips_zhirui_2', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.xiaomi_philips_zhirui_2'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.xiaomi_philips_zhirui_2'}, 'fields': {'title': 'Downlight cozinha janela', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-track-light', 'icon_off': 'mdi-track-light'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-track-light', 'icon_off': 'mdi-track-light', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-yeelight-color1-7811dc6b98cb"] = new baselight("default-yeelight-color1-7811dc6b98cb", "", "default", {'widget_type': 'baselight', 'entity': 'light.yeelight_color1_7811dc6b98cb', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.yeelight_color1_7811dc6b98cb'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.yeelight_color1_7811dc6b98cb'}, 'fields': {'title': 'Aplique esquerdo sala', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-lamp', 'icon_off': 'mdi-lamp'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-lamp', 'icon_off': 'mdi-lamp', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-yeelight-color1-7811dc6b9b10"] = new baselight("default-yeelight-color1-7811dc6b9b10", "", "default", {'widget_type': 'baselight', 'entity': 'light.yeelight_color1_7811dc6b9b10', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.yeelight_color1_7811dc6b9b10'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.yeelight_color1_7811dc6b9b10'}, 'fields': {'title': 'Aplique direito sala', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-lamp', 'icon_off': 'mdi-lamp'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-lamp', 'icon_off': 'mdi-lamp', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-yeelight-color1-7811dce0fe41"] = new baselight("default-yeelight-color1-7811dce0fe41", "", "default", {'widget_type': 'baselight', 'entity': 'light.yeelight_color1_7811dce0fe41', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.yeelight_color1_7811dce0fe41'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.yeelight_color1_7811dce0fe41'}, 'fields': {'title': 'Candeeiro Mafalda', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-floor-lamp', 'icon_off': 'mdi-floor-lamp'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-floor-lamp', 'icon_off': 'mdi-floor-lamp', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-yeelight-color1-7811dce12676"] = new baselight("default-yeelight-color1-7811dce12676", "", "default", {'widget_type': 'baselight', 'entity': 'light.yeelight_color1_7811dce12676', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.yeelight_color1_7811dce12676'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.yeelight_color1_7811dce12676'}, 'fields': {'title': 'Aplique Entrada', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-coach-lamp', 'icon_off': 'mdi-coach-lamp', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-leds-armario-sala"] = new baselight("default-leds-armario-sala", "", "default", {'widget_type': 'baselight', 'entity': 'light.leds_armario_sala', 'post_service_active': {'service': 'homeassistant/turn_on', 'entity_id': 'light.leds_armario_sala'}, 'post_service_inactive': {'service': 'homeassistant/turn_off', 'entity_id': 'light.leds_armario_sala'}, 'fields': {'title': 'Leds TV', 'title2': '', 'icon': '', 'units': '%', 'level': '', 'state_text': '', 'icon_style': ''}, 'icons': {'icon_on': 'mdi-led-strip', 'icon_off': 'mdi-led-strip'}, 'static_icons': {'icon_up': 'fas-plus', 'icon_down': 'fas-minus'}, 'static_css': {'title_style': 'color: #fff;', 'title2_style': 'color: #fff;', 'state_text_style': 'color: #fff;', 'level_style': 'color: #fff;', 'unit_style': 'color: #fff;', 'level_up_style': 'color: #888;', 'level_down_style': 'color: #888;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;'}, 'icon_on': 'mdi-led-strip', 'icon_off': 'mdi-led-strip', 'icon_style_active': 'color: red;', 'icon_style_inactive': 'color: green;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-load-secundario-panel"] = new basejavascript("default-load-secundario-panel", "", "default", {'widget_type': 'basejavascript', 'fields': {'title': 'Painel Secundário', 'title2': '', 'icon': '', 'icon_style': ''}, 'icons': {'icon_active': 'fas-spinner fa-spin', 'icon_inactive': 'mdi-home-floor-2'}, 'static_css': {'title_style': 'color: Black;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_active_style': 'color: #fff;', 'icon_inactive_style': 'color: blue;'}, 'static_icons': [], 'icon_inactive': 'mdi-home-floor-2', 'dashboard': 'segundo_painel', 'title_style': 'color: Black;', 'icon_inactive_style': 'color: blue;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-load-radio-panel"] = new basejavascript("default-load-radio-panel", "", "default", {'widget_type': 'basejavascript', 'fields': {'title': 'Rádio', 'title2': '', 'icon': '', 'icon_style': ''}, 'icons': {'icon_active': 'fas-spinner fa-spin', 'icon_inactive': 'mdi-radio'}, 'static_css': {'title_style': 'color: Black;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_active_style': 'color: #fff;', 'icon_inactive_style': 'color: blue;'}, 'static_icons': [], 'icon_inactive': 'mdi-radio', 'dashboard': 'radio', 'title_style': 'color: Black;', 'icon_inactive_style': 'color: blue;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    
        widgets["default-load-aspirador-panel"] = new basejavascript("default-load-aspirador-panel", "", "default", {'widget_type': 'basejavascript', 'fields': {'title': 'RoboRock S50', 'title2': '', 'icon': '', 'icon_style': ''}, 'icons': {'icon_active': 'fas-spinner fa-spin', 'icon_inactive': 'mdi-robot-vacuum'}, 'static_css': {'title_style': 'color: Black;', 'title2_style': 'color: #fff;', 'widget_style': 'background-color: #444;'}, 'css': {'icon_active_style': 'color: #fff;', 'icon_inactive_style': 'color: black;'}, 'static_icons': [], 'icon_inactive': 'mdi-robot-vacuum', 'dashboard': 'aspirador', 'title_style': 'color: Black;', 'icon_inactive_style': 'color: black;', 'use_comma': 0, 'precision': 1, 'use_hass_icon': 0, 'namespace': 'default'})
    

    // Setup click handler to cancel timeout navigations

    $( ".gridster" ).click(function(){
        clearTimeout(myTimeout);
        if (myTimeoutSticky) {
            myTimeout = setTimeout(function() { navigate(myTimeoutUrl); }, myTimeoutDelay);
        }
    });

    // Set up timeout

    var myTimeout;
    var myTimeoutUrl;
    var myTimeoutDelay;
    var myTimeoutSticky = 0;

    if (location.search != "")
    {
        var query = location.search.substr(1);
        var result = {};
        query.split("&").forEach(function(part) {
        var item = part.split("=");
        result[item[0]] = decodeURIComponent(item[1]);
        });

        if ("timeout" in result && "return" in result)
        {
            url = result.return
            argcount = 0
            for (arg in result)
            {
                if (arg != "timeout" && arg != "return" && arg != "sticky")
                {
                    if (argcount == 0)
                    {
                        url += "?";
                    }
                    else
                    {
                        url += "?";
                    }
                    argcount ++;
                    url += arg + "=" + result[arg]
                }
            }
            if ("sticky" in result)
            {
                myTimeoutSticky = (result.sticky == "1");
            }
            myTimeoutUrl = url;
            myTimeoutDelay = result.timeout * 1000;
            myTimeout = setTimeout(function() { navigate(url); }, result.timeout * 1000);
        }
    }

    // Start listening for HA Events

    
    if (location.protocol == 'https:')
    {
        wsprot = "wss:"
    }
    else
    {
        wsprot = "ws:"
    }
    var stream_url = wsprot + '//' + location.host + '/stream'
    

    ha_status(stream_url, "Casa Inteligente", widgets, "ws");

});