homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
  customize:
    binary_sensor.door_window_sensor_158d0002bfae0f:
      friendly_name: Porta Direita
      icon: mdi:fridge
    binary_sensor.door_window_sensor_10002bf9d6d:
      friendly_name: Porta Esquerda
    light.xiaomi_philips_zhirui:
      friendly_name: Downlight cozinha
      icon: mdi:lightbulb-on
    light.xiaomi_philips_zhirui_1:
      friendly_name: Downlight cozinha 1
      icon: mdi:lightbulb-on
    light.xiaomi_philips_zhirui_2:
      friendly_name: Downlight cozinha 2
      icon: mdi:lightbulb-on
    light.leds_armario:
      icon: mdi:lightbulb-on
    binary_sensor.movimento_cozinha:
      friendly_name: Sensor de Movimento Cozinha
      icon: mdi:run
    sensor.lightlevel_15:
      friendly_name: Sensor LX
      icon: mdi:brightness-4
    switch.tomada_fervedor:
      friendly_name: Ligar Fervedor
      icon: mdi:power
    switch.tomada_microndas:
      friendly_name: Ligar Microndas
      icon: mdi:power
    automation.ligar_downlights_06h30_23h:
      icon: mdi:bell-ring
    automation.ligar_downlights_23h_02h:  
      icon: mdi:bell-ring
    automation.ligar_downlights_02h_06h30: 
      icon: mdi:bell-ring
    automation.desligar_downlights_06h30_09h:
      icon: mdi:bell-ring
    automation.desligar_downlights_09h_11h:
      icon: mdi:bell-ring
    automation.desligar_downlights_11h_23h:
      icon: mdi:bell-ring
    automation.desligar_downlights_23h_06h30:
      icon: mdi:bell-ring      

###############################################################################
#                                                                             #
#                               S E N S O R                                   #
#                                                                             #
############################################################################### 

###############################################################################
#                                                                             #
#                              S W I T C H                                    #
#                                                                             #
###############################################################################
switch:
  - platform: mqtt
    name: "Tomada Microndas"
    state_topic: "stat/microndas/POWER"
    command_topic: "cmnd/microndas/power"
    availability_topic: "tele/microndas/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

###############################################################################
#                                                                             #
#                                L I G H T S                                  #
#                                                                             #
###############################################################################      
light:
  - platform: xiaomi_miio
    name: Xiaomi Philips zhirui
    host: !secret xiaomi_philips_zhirui_ip
    token: !secret xiaomi_philips_zhirui_token
    model: philips.light.downlight

  - platform: xiaomi_miio
    name: Xiaomi Philips zhirui 1
    host: !secret xiaomi_philips_zhirui_1_ip
    token: !secret xiaomi_philips_zhirui_1_token
    model: philips.light.downlight

  - platform: xiaomi_miio
    name: Xiaomi Philips zhirui 2
    host: !secret xiaomi_philips_zhirui_2_ip
    token: !secret xiaomi_philips_zhirui_2_token
    model: philips.light.downlight

  - platform: mqtt
    name: "Leds Armário"
    state_topic: "stat/merciaria/POWER"
    command_topic: "cmnd/merciaria/power"
    availability_topic: "tele/merciaria/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

# automações

  - alias: Ligar Leds Despensa Merciaria
    initial_state: true
    trigger:
      platform: state
      entity_id: group.sensores_despensa
      from: 'off'
      to: 'on'
    action:
      - service: light.turn_on
        entity_id:
          - light.leds_armario

  - alias: Desligar Leds Despensa Merciaria
    initial_state: true
    trigger:
      platform: state
      entity_id: group.sensores_despensa
      from: 'on'
      to: 'off'
    action:
      - service: light.turn_off
        entity_id: 
          - light.leds_armario

  - alias: Ligar Downlights 06h30 22h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.movimento_cozinha
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '06:30:00'
      before: '22:00:00'
    - condition: numeric_state
      entity_id: sensor.lightlevel_15
      below: 60
    action:
      - service: xiaomi_miio.light_set_scene
        data:
          entity_id: 
            - light.xiaomi_philips_zhirui
            - light.xiaomi_philips_zhirui_1
            - light.xiaomi_philips_zhirui_2
          scene: 1

  - alias: Ligar Downlights 22h 02h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.movimento_cozinha
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '22:00:00'
      before: '02:00:00'
    - condition: numeric_state
      entity_id: sensor.lightlevel_15
      below: 60
    action:
      - service: xiaomi_miio.light_set_scene
        data:
          entity_id:
            - light.xiaomi_philips_zhirui_1
            - light.xiaomi_philips_zhirui_2
          scene: 3
      - service: light.turn_off
        entity_id: light.xiaomi_philips_zhirui



#  - alias: Ligar Downlights 22h 02h teste
#    initial_state: true
#    trigger:
#      platform: state
#      entity_id: binary_sensor.movimento_cozinha
#      from: 'off'
#      to: 'on'
#    condition:
#    - condition: time
#      after: '22:00:00'
#      before: '02:00:00'
#    - condition: numeric_state
#      entity_id: sensor.lightlevel_15
#      below: 60
#    action:
#      - delay:
#          seconds: 4
#      - service: xiaomi_miio.light_set_scene
#        data:
#          entity_id: light.xiaomi_philips_zhirui
#          scene: 1
#      - delay:
#          seconds: 6
#      - service: light.xiaomi_miio_set_scene
#        data:
#          entity_id: light.xiaomi_philips_zhirui_1
#          scene: 2
#      - delay:
#          seconds: 2
#      - service: light.xiaomi_miio_set_scene
#        data:
#          entity_id: light.xiaomi_philips_zhirui_2
#          scene: 3


  - alias: Ligar Downlights 02h 06h30
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.movimento_cozinha
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '02:00:00'
      before: '06:30:00'
    - condition: numeric_state
      entity_id: sensor.lightlevel_15
      below: 60
    action:
      - service: xiaomi_miio.light_set_scene
        data:
          entity_id:
            - light.xiaomi_philips_zhirui_1
            - light.xiaomi_philips_zhirui_2
          scene: 4
      - service: light.turn_off
        entity_id: light.xiaomi_philips_zhirui
        
  - alias: Desligar Downlights 06h30 09h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.movimento_cozinha
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    condition:
    - condition: time
      after: '06:30:00'
      before: '09:00:00'
    action:
      - service: light.turn_off
        entity_id: 
          - light.xiaomi_philips_zhirui
          - light.xiaomi_philips_zhirui_1
          - light.xiaomi_philips_zhirui_2

  - alias: Desligar Downlights 09h 11h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.movimento_cozinha
      from: 'on'
      to: 'off'
      for:
        minutes: 2
    condition:
    - condition: time
      after: '09:00:00'
      before: '11:00:00'
    action:
      - service: light.turn_off
        entity_id: 
          - light.xiaomi_philips_zhirui
          - light.xiaomi_philips_zhirui_1
          - light.xiaomi_philips_zhirui_2

  - alias: Desligar Downlights 11h 22h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.movimento_cozinha
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    condition:
    - condition: time
      after: '11:00:00'
      before: '22:00:00'
    action:
      - service: light.turn_off
        entity_id: 
          - light.xiaomi_philips_zhirui
          - light.xiaomi_philips_zhirui_1
          - light.xiaomi_philips_zhirui_2

  - alias: Desligar Downlights 22h 06h30
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.movimento_cozinha
      from: 'on'
      to: 'off'
      for:
        minutes: 2
    condition:
    - condition: time
      after: '22:00:00'
      before: '06:30:00'
    action:
      - service: light.turn_off
        entity_id: 
          - light.xiaomi_philips_zhirui
          - light.xiaomi_philips_zhirui_1
          - light.xiaomi_philips_zhirui_2

#  - alias: Desligar Downlights a Cima dos 61 lx
#    initial_state: false
#    trigger:
#      platform: state
#      entity_id: binary_sensor.motion_sensor_158d0001f9d417
#      to: 'off'
#      for: 
#        seconds: 15
#    condition:
#    - condition: time
#      after: '06:00:00'
#      before: '23:00:00'
#    - condition: numeric_state
#      entity_id: sensor.lightlevel_15
#      above: 61
#    action:
#      - service: light.turn_off
#        entity_id: 
#          - light.xiaomi_philips_zhirui
#          - light.xiaomi_philips_zhirui_1
#          - light.xiaomi_philips_zhirui_2

#  - alias: Desligar Downlights a Cima dos 61 lx 2
#    initial_state: false
#    trigger:
#      platform: state
#      entity_id: binary_sensor.motion_sensor_158d0001f9d417
#      to: 'off'
#      for: 
#        seconds: 15
#    condition:
#    - condition: time
#      after: '23:00:00'
#      before: '06:00:00'
#    - condition: numeric_state
#      entity_id: sensor.lightlevel_15
#      above: 61
#    action:
#      - service: light.turn_off
#        entity_id: 
#          - light.xiaomi_philips_zhirui
#          - light.xiaomi_philips_zhirui_1
#          - light.xiaomi_philips_zhirui_2

###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             #
###############################################################################      
group:

  Sensores Despensa:
    name: Sensores Despensa
    entities:
      - binary_sensor.openclose_22
      - binary_sensor.porta_2_despensa