homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################
  customize:
    binary_sensor.door_window_sensor_158d00024e0c7b:
      friendly_name: Porta do Escritório
      icon: mdi:door-open
    light.downlight_direito:
      icon: mdi:lightbulb-on
    light.downlight_esquerdo:
      icon: mdi:lightbulb-on
    sensor.temperature_158d00023203e4:
      friendly_name: Sensor de Temperatura do escritório
      icon: mdi:temperature-celsius
    sensor.humidity_158d00023203e4:
      friendly_name: Sensor de Humidade do escritório
      icon: mdi:water-percent

###############################################################################
#                                                                             #
#                            L I G H T S                                      #
#                                                                             #
###############################################################################
light:
  - platform: mqtt
    name: "Downlight Esquerdo"
    state_topic: "stat/escritorio/POWER1"
    command_topic: "cmnd/escritorio/power1"
    availability_topic: "tele/escritorio/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

  - platform: mqtt
    name: "Downlight Direito"
    state_topic: "stat/escritorio/POWER2"
    command_topic: "cmnd/escritorio/power2"
    availability_topic: "tele/escritorio/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

  - alias: Liga Luz do Escritório
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.openclose_7
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: "+00:01:00"
      - condition: sun
        before: sunrise
    action:
      - service: light.turn_on
        entity_id:
          - light.downlight_direito
          - light.downlight_esquerdo

  - alias: Desliga Luz do Escritório
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.openclose_7
      to: 'off'
      for:
        minutes: 1
    condition:
    - condition: state
      entity_id: 'switch.monitor_do_pc'
      state: 'off'
    action:
      - service: light.turn_off
        data_template:
          entity_id:
            - light.downlight_direito
            - light.downlight_esquerdo

#notificações

  - alias: Porta Escritório Aberta
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.openclose_7
      from: 'off'
      to: 'on'
    action:
      service: notify.telegram
      data:
        title: "Porta do Escritório"
        message: "Está Aberta. Bateria: {{ states('sensor.openclose_7_battery_level') }}%."

  - alias: Porta Escritório Fechada
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.openclose_7
      from: 'on'
      to: 'off'
    action:
      service: notify.telegram
      data:
        title: "Porta do Escritório"
        message: "Está fechada. Bateria: {{ states('sensor.openclose_7_battery_level') }}%."

#  - alias: Porta do escritório aberta á 10 mim
#    initial_state: false
#    trigger:
#      platform: state
#      entity_id: binary_sensor.door_window_sensor_158d00024e0c7b
#      from: 'off'
#      to: 'on'
#      for:
#        minutes: 10
#    action:
#      service: notify.telegram
#      data:
#        title: "Porta do Escritório"
#        message: "Está aberta á 10 mim"

  - alias: Porta escritorio continua aberta
    initial_state: true
    trigger:
      platform: time_pattern
      minutes: '/10'
    condition:
      - condition: state
        entity_id: binary_sensor.openclose_7
        state: 'on'
      - condition: state
        entity_id: person.bruno
        state: not_home
    action:
      service: notify.telegram
      data:
        title: "Porta do Escritório"
        message: "Continua aberta"