homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
  customize:
    light.candeeiro_patio_1:
      icon: mdi:lightbulb-on
    light.candeeiro_patio_2:
      icon: mdi:lightbulb-on
    light.candeeiro_patio_3:
      icon: mdi:lightbulb-on
    light.candeeiro_patio_4:
      icon: mdi:lightbulb-on
###############################################################################
#                                                                             #
#                         S W I T C H                                         #
#                                                                             #
############################################################################### 
light:
  - platform: mqtt
    name: "Candeeiro pátio 1"
    state_topic: "stat/lamp1_2/POWER1"
    command_topic: "cmnd/lamp1_2/power1"
    availability_topic: "tele/lamp1_2/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

  - platform: mqtt
    name: "Candeeiro pátio 2"
    state_topic: "stat/lamp1_2/POWER2"
    command_topic: "cmnd/lamp1_2/power2"
    availability_topic: "tele/lamp1_2/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

  - platform: mqtt
    name: "Candeeiro pátio 3"
    state_topic: "stat/lamp3_4/POWER1"
    command_topic: "cmnd/lamp3_4/power1"
    availability_topic: "tele/lamp3_4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

  - platform: mqtt
    name: "Candeeiro pátio 4"
    state_topic: "stat/lamp3_4/POWER2"
    command_topic: "cmnd/lamp3_4/power2"
    availability_topic: "tele/lamp3_4/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

  - alias: Ligar Iluminação do canteiro
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      from: 'off'
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: "+00:10:00"
      - condition: sun
        before: sunrise
    action:
      - delay:
          seconds: 5
      - service: light.turn_on
        data:
          entity_id: light.candeeiro_patio_1
      - delay:
          seconds: 3 
      - service: light.turn_on
        data:
          entity_id: light.candeeiro_patio_2
      - delay:
          seconds: 3
      - service: light.turn_on
        data:
          entity_id: light.candeeiro_patio_3
      - delay:
          seconds: 3
      - service: light.turn_on
        data:
          entity_id: light.candeeiro_patio_4

  - alias: Desligar Iluminação do canteiro
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      to: 'off'
      for:
        minutes: 3
    action:
      - delay:
          seconds: 2
      - service: light.turn_off
        data:
          entity_id: light.candeeiro_patio_4
      - delay:
          seconds: 2
      - service: light.turn_off
        data:
          entity_id: light.candeeiro_patio_3
      - delay:
          seconds: 2
      - service: light.turn_off
        data:
          entity_id: light.candeeiro_patio_2
      - delay:
          seconds: 2
      - service: light.turn_off
        data:
          entity_id: light.candeeiro_patio_1

#conbee para iluminacao do patio Pai

  - alias: Ligar iluminacao patio 2 lampadas
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: iluminacao_exterior
        event: 1000
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
    action:
      service_template: >
       {% if is_state('group.duas_lampadas_do_patio', 'off') %}
       light.turn_on  
       {%- elif is_state('group.duas_lampadas_do_patio', 'on') -%}
       light.turn_off
       {% endif %}
      entity_id: group.duas_lampadas_do_patio

  - alias: Ligar iluminacao patio
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: iluminacao_exterior
        event: 1004
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
    action:
      service_template: >
       {% if is_state('group.lampadas_do_patio', 'off') %}
       light.turn_on  
       {%- elif is_state('group.lampadas_do_patio', 'on') -%}
       light.turn_off
       {% endif %}
      entity_id: group.lampadas_do_patio

#conbee para iluminacao do patio Bruno

  - alias: Ligar iluminacao patio 2 lampadas Bruno
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: portao_e_iluminacao
        event: 1005
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
    action:
      service_template: >
       {% if is_state('group.duas_lampadas_do_patio', 'off') %}
       light.turn_on  
       {%- elif is_state('group.duas_lampadas_do_patio', 'on') -%}
       light.turn_off
       {% endif %}
      entity_id: group.duas_lampadas_do_patio

  - alias: Ligar iluminacao patio Bruno
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: portao_e_iluminacao
        event: 1006
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
    action:
      service_template: >
       {% if is_state('group.lampadas_do_patio', 'off') %}
       light.turn_on  
       {%- elif is_state('group.lampadas_do_patio', 'on') -%}
       light.turn_off
       {% endif %}
      entity_id: group.lampadas_do_patio

###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             #
###############################################################################
group:

  Duas lâmpadas do pátio:
    name: Duas lâmpadas do pátio
    entities:
      - light.candeeiro_patio_2
      - light.candeeiro_patio_3

  Lâmpadas do pátio:
    name: Lâmpadas do pátio
    entities:
      - light.candeeiro_patio_1
      - light.candeeiro_patio_2
      - light.candeeiro_patio_3
      - light.candeeiro_patio_4
      - light.iluminacao_das_garagens