homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
  customize:
    light.yeelight_color1_7811dce12676:
      friendly_name: Luz Exterior Porta Entrada
      icon: mdi:lightbulb-on
    light.gateway_light_7811dcb38555:
      friendly_name: Led do Gateway
      icon: mdi:lightbulb-on
    binary_sensor.porta_de_entrada:
      friendly_name: Porta de Entrada
    binary_sensor.switch_158d00015aa37d:
      friendly_name: Interruptor Portão
      icon: mdi:light-switch

###############################################################################
#                                                                             #
#                               S E N S O R                                   #
#                                                                             #
############################################################################### 
sensor:
  - platform: template
    sensors:
      porta_rua:
        friendly_name: "Porta da Rua"
        value_template: >-
          {% if is_state('binary_sensor.porta_de_entrada', 'on') %}
            Aberta
          {% else %}
            Fechada
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.porta_de_entrada', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
###############################################################################
#                                                                             #
#                         L I G H T                                           #
#                                                                             #
###############################################################################      
yeelight:
  devices:
    !secret yeelight_exterior_ip:
      name: yeelight_color1_7811dce12676
      model: color1
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

#automaçóes gatewayy

  - alias: Liga Luz do Gateway
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.porta_de_entrada
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: "+00:15:00"
      - condition: sun
        before: sunrise
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.gateway_light_7811dcb38555
          brightness: 200
          color_name: deepskyblue

  - alias: Desliga Luz do Gateway
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.porta_de_entrada
      to: 'off'
      for:
        minutes: 2
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.gateway_light_7811dcb38555

#automação luz rua

  - alias: Liga Luz do Exterior
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.porta_de_entrada
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: "+00:15:00"
      - condition: sun
        before: sunrise
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.yeelight_color1_7811dce12676
          brightness: 255
          kelvin: 5000

  - alias: Desliga Luz do Exterior
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.porta_de_entrada
      to: 'off'
      for:
        minutes: 4
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.yeelight_color1_7811dce12676

#notificações

#  - alias: Porta Aberta
#    initial_state: false
#    trigger:
#      platform: state
#      entity_id: binary_sensor.porta_de_entrada
#      from: 'off'
#      to: 'on'
#    action:
#      service: notify.telegram
#      data:
#        title: "Porta de entrada "
#        message: "está aberta"

#  - alias: Porta Fechada
#    initial_state: false
#    trigger:
#      platform: state
#      entity_id: binary_sensor.porta_de_entrada
#      from: 'on'
#      to: 'off'
#    action:
#      service: notify.telegram
#      data:
#        title: "Porta de entrada "
#        message: "está fechada"

#  - alias: Porta de entrada aberta á 10 mim
#    initial_state: false
#    trigger:
#      platform: state
#      entity_id: binary_sensor.porta_de_entrada
#      from: 'off'
#      to: 'on'
#      for:
#        minutes: 10
#    action:
#      service: notify.telegram
#      data:
#        title: "Porta de entrada "
#        message: "está aberta á 10 mim"

  - alias: Porta continua aberta
    initial_state: true
    trigger:
      platform: time_pattern
      minutes: '/10'
    condition:
      - condition: state
        entity_id: binary_sensor.porta_de_entrada
        state: 'on'
    action:
      service: notify.telegram
      data:
        title: "Porta de entrada "
        message: "continua aberta"

#desligar notificações em casa

  - alias: Ligar Notificações quando fora casa
    initial_state: true
    trigger:
      - platform: state
        entity_id: group.wifi
        from: 'home'
        to: 'not_home'
    action:
      - service: automation.turn_on
        entity_id: 
          - automation.porta_aberta
          - automation.porta_fechada

  - alias: Desligar Notificações quando em casa
    initial_state: true
    trigger:
      - platform: state
        entity_id: group.wifi
        from: 'not_home'
        to: 'home'
    action:
      - service: automation.turn_off
        entity_id: 
          - automation.porta_aberta
          - automation.porta_fechada