homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
  customize:
    binary_sensor.0x00158d0002e7f816_contact:
      friendly_name: Portão do Jardim
      icon: mdi:gate
    light.iluminacao_do_jardim:
      icon: mdi:lightbulb-on
    light.iluminacao_lateral:
      icon: mdi:lightbulb-on
    light.iluminacao_coberto:
      icon: mdi:lightbulb-on
###############################################################################
#                                                                             #
#                         L I G T H S                                         #
#                                                                             #
############################################################################### 
light:
  - platform: mqtt
    name: "Iluminação do Jardim"
    state_topic: "stat/jardim_iluminacao/POWER1"
    command_topic: "cmnd/jardim_iluminacao/power1"
    availability_topic: "tele/jardim_iluminacao/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

  - platform: mqtt
    name: "Iluminação Lateral"
    state_topic: "stat/jardim_iluminacao/POWER2"
    command_topic: "cmnd/jardim_iluminacao/power2"
    availability_topic: "tele/jardim_iluminacao/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

  - platform: mqtt
    name: "Iluminação Coberto"
    state_topic: "stat/iluminacao_coberto/POWER"
    command_topic: "cmnd/iluminacao_coberto/power"
    availability_topic: "tele/iluminacao_coberto/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
###############################################################################
#                                                                             #
#                         S E N S O R   P O R T Ã O                           #
#                                                                             #
###############################################################################      
sensor:
  - platform: template
    sensors:
      portao_jardim:
        friendly_name: "Estado Portão do Jardim"
        value_template: >-
          {% if is_state('binary_sensor.0x00158d0002e7f816_contact', 'on') %}       
            Portão Aberto
          {% else %}
            Portão Fechado
          {% endif %}
#        icon_template: >-
#          {% if is_state('binary_sensor.0x00158d0002e7f816_contact', 'on') %}
#            mdi:door-open
#          {% else %}
#            mdi:door-closed
#          {% endif %}
        entity_picture_template: >-
          {% if is_state('binary_sensor.0x00158d0002e7f816_contact', 'on') %}
           /local/icon/open_gate.png
          {% else %}
            /local/icon/close_gate.png
          {% endif %}
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

  - alias: Ligar Iluminação do Jardim
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.0x00158d0002e7f816_contact
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: "+00:10:00"
      - condition: sun
        before: sunrise
    action:
      - service: light.turn_on
        entity_id:
          - light.iluminacao_lateral
          - light.iluminacao_do_jardim
          - light.iluminacao_coberto

  - alias: Desligar Iluminação do Jardim
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.0x00158d0002e7f816_contact
      to: 'off'
      for:
        minutes: 2
    action:
      - service: light.turn_off
        data_template:
          entity_id:
            - light.iluminacao_do_jardim
            - light.iluminacao_lateral
            - light.iluminacao_coberto

#conbee para iluminacao do jardim

  - alias: Ligar iluminacao do jardim e coberto
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: iluminacao_exterior
        event: 1005
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
    action:
      service_template: >
       {% if is_state('group.iluminacao_do_jardim', 'off') %}
       light.turn_on  
       {%- elif is_state('group.iluminacao_do_jardim', 'on') -%}
       light.turn_off
       {% endif %}
      entity_id: group.iluminacao_do_jardim

  - alias: Ligar iluminacao do jardim e coberto Bruno
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: portao_e_iluminacao
        event: 1010
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
    action:
      service_template: >
       {% if is_state('group.iluminacao_do_jardim', 'off') %}
       light.turn_on  
       {%- elif is_state('group.iluminacao_do_jardim', 'on') -%}
       light.turn_off
       {% endif %}
      entity_id: group.iluminacao_do_jardim

###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             #
###############################################################################      
group:

  Iluminação do jardim:
    name: Iluminação do jardim
    entities:
      - light.iluminacao_do_jardim
      - light.iluminacao_lateral
      - light.iluminacao_coberto
