homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################
  customize:
    light.yeelight_color1_7811dce0fe41:
      friendly_name: Candeeiro
      icon: mdi:lightbulb-on
    binary_sensor.presence_19:
      friendly_name: Sensor de Movimento Mafalda
      icon: mdi:run
    sensor.movimento_q_mafalda:
      friendly_name: Sensor LX Mafalda
      icon: mdi:brightness-4
    light.Teto_quarto_mafalda:
      icon: mdi:lightbulb-on

###############################################################################
#                                                                             #
#                           L U Z E S                                         #
#                                                                             #
###############################################################################
yeelight:
  devices:
    !secret yeelight_q_mafalda_ip:
      name: yeelight_color1_7811dce0fe41
      model: color1

light:
  - platform: mqtt
    name: "Teto Quarto Mafalda"
    state_topic: "shellies/shelly1-944B35/relay/0"
    command_topic: "shellies/shelly1-944B35/relay/0/command"
    payload_on: "on"
    payload_off: "off"
    retain: false

###############################################################################
#                                                                             #
#                              S H E L L Y                                    #
#                                                                             #
###############################################################################   
#switch:
# - platform: rest
#    name: "Shelly Mafalda"
#    scan_interval: 2
#    resource: http://192.168.1.104/relay/0
#    body_on: 'turn=on'
#    body_off: 'turn=off'
#    is_on_template: '{{ value_json.ison == true}}'
#    headers:
#      content-type: application/x-www-form-urlencoded
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:


#automações leds tecto fim de semana e feriados Mafalda

  - alias: Ligar luzes teto Mafalda
    initial_state: true
    trigger:
      platform: state
      entity_id: light.Teto_quarto_afalda
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_color1_7811dce0fe41

  - alias: Desligar luzes teto mafalda 17h 22h
    initial_state: true
    trigger:
      platform: state
      entity_id: light.ceiling_lights_living_room
      from: 'on'
      to: 'off'
    condition:
    - condition: time
      after: '17:00:00'
      before: '22:00:00'
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.yeelight_color1_7811dce0fe41
        data:
          brightness: 200
          kelvin: 5000

#automação quarto mafalda durante a semana

  - alias: Ligar Candeeiro 17h00 20h00
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: time
      after: '17:00:00'
      before: '20:00:00'
    - condition: numeric_state
      entity_id: sensor.movimento_q_mafalda
      below: 20
    action:
      - service: light.turn_on
        entity_id: light.yeelight_color1_7811dce0fe41
        data:
          brightness: 255
          kelvin: 5000

  - alias: Ligar Candeeiro 20h00 22h00
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: time
      after: '20:00:00'
      before: '22:00:00'
    - condition: numeric_state
      entity_id: sensor.movimento_q_mafalda
      below: 20
    action:
      - service: light.turn_on
        entity_id: light.yeelight_color1_7811dce0fe41
        data:
          brightness: 50
          kelvin: 3000

  - alias: Desligar Candeeiro 17h00 22h00
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      from: 'on'
      to: 'off'
      for:
        minutes: 3
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: time
      after: '17:00:00'
      before: '22:00:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_color1_7811dce0fe41


#automação mudar fraldas quarto durante a semana

  - alias: Mudar Fraldas Quarto 22h00 07h00
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: time
      after: '22:00:00'
      before: '07:00:00'
    - condition: numeric_state
      entity_id: sensor.movimento_q_mafalda
      below: 20
    action:
      - service: light.turn_on
        entity_id: light.yeelight_color1_7811dce0fe41
        data:
          brightness: 50
          color_name: orangered

  - alias: Mudar Fraldas Quarto 07h00 08h00
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: time
      after: '07:00:00'
      before: '08:00:00'
    - condition: numeric_state
      entity_id: sensor.movimento_q_mafalda
      below: 20
    action:
      - service: light.turn_on
        entity_id: light.yeelight_color1_7811dce0fe41
        data:
          brightness: 200
          color_name: orangered

  - alias: Desligar Mudar Fraldas Quarto 22h00 08h00
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      from: 'on'
      to: 'off'
      for:
        minutes: 2
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: time
      after: '22:00:00'
      before: '08:00:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_color1_7811dce0fe41

#automação mudar fraldas quarto durante o fim de seamana

  - alias: Ligar Candeeiro fim de semana 17h 22h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    - condition: time
      after: '17:00:00'
      before: '22:00:00'
    - condition: numeric_state
      entity_id: sensor.movimento_q_mafalda
      below: 40
    action:
      - service: light.turn_on
        entity_id: light.yeelight_color1_7811dce0fe41
        data:
          brightness: 200
          kelvin: 5000

  - alias: Ligar Candeeiro fim de semana 22h 9h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    - condition: time
      after: '22:00:00'
      before: '09:00:00'
    - condition: numeric_state
      entity_id: sensor.movimento_q_mafalda
      below: 20
    action:
      - service: light.turn_on
        entity_id: light.yeelight_color1_7811dce0fe41
        data:
          brightness: 150
          color_name: orangered

  - alias: Desligar candeeiro fim de semana 17h 22h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      from: 'on'
      to: 'off'
      for:
        minutes: 3
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    - condition: time
      after: '17:00:00'
      before: '22:00:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_color1_7811dce0fe41

  - alias: Desligar candeeiro fim de semana 22h 09h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.presence_19
      from: 'on'
      to: 'off'
      for:
        minutes: 2
    condition:
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'off'
    - condition: time
      after: '22:00:00'
      before: '09:00:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_color1_7811dce0fe41

#Zigbee

#  - alias: Ligar luz
#    initial_state: true
#    trigger: 
#      platform: state
#      entity_id: sensor.botao_leds_click
#      to: 'on'
#    action:
#      - service: light.turn_on
#        entity_id: light.yeelight_color1_7811dce0fe41
#        data:
#          brightness: 10
#          color_name: orangered

#  - alias: Desligar luz
#    initial_state: true
#    trigger: 
#      platform: state
#      entity_id: sensor.botao_leds_click
#      to: 'off'
#    action:
#      - service: light.turn_off
#        entity_id: light.yeelight_color1_7811dce0fe41

#  - alias: Desligar luzes da sala e cozinha
#    initial_state: true
#    trigger: 
#      platform: state
#      entity_id: sensor.botao_leds_click
#      to: 'brightness_down'
#    action:
#      - service: light.turn_off
#        entity_id: 
#          - light.yeelight_color1_7811dc6b98cb
#          - light.yeelight_color1_7811dc6b9b10
#          - light.xiaomi_philips_zhirui
#          - light.xiaomi_philips_zhirui_1
#          - light.xiaomi_philips_zhirui_2
#          - light.leds_armario_sala

#conbee


  - alias: Ligar luz
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: botao_quarto_mafalda
        event: 1002
    action:
      - service: light.turn_on
        entity_id: light.yeelight_color1_7811dce0fe41
        data:
          brightness: 10
          color_name: orangered

  - alias: Desligar luz
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: botao_quarto_mafalda
        event: 2002
    action:
      - service: light.turn_off
        entity_id: light.yeelight_color1_7811dce0fe41

  - alias: Desligar luzes da sala e cozinha
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: botao_quarto_mafalda
        event: 2001
    action:
      - service: light.turn_off
        entity_id: 
          - light.yeelight_color1_7811dc6b98cb
          - light.yeelight_color1_7811dc6b9b10
          - light.xiaomi_philips_zhirui
          - light.xiaomi_philips_zhirui_1
          - light.xiaomi_philips_zhirui_2
          - light.leds_armario_sala