homeassistant:
  customize:
    person.bruno:
      entity_picture: "/local/adlocal/device_trackers/bruno.jpg"
    person.armanda:
      entity_picture: "/local/device_trackers/armanda.jpg"
###############################################################################
#                                                                             #
#                                  P E R S O N                                #
#                                                                             #
############################################################################### 
person:
  - name: Bruno
    id: bruno1981
    device_trackers:
      - device_tracker.bruno_melo
      - device_tracker.bruno_nmap
  - name: Armanda
    id: armanda1984
    device_trackers:
      - device_tracker.armanda_rodrigues
      - device_tracker.armanda_nmap
  - name: Armando
    id: armando1962
    device_trackers:
      - device_tracker.armando_melo
      - device_tracker.mando_nmap

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

#Automações para notificações

  - alias: Notificar quando Bruno estiver ligado ao wifi
    initial_state: true
    trigger:
    - platform: state
      entity_id: person.bruno
      from: 'not_home'
      to: 'home'
    action:
      service: notify.telegram
      data:
        title: "Bruno "
        message: "acabou de se ligar á rede."
        data:
          photo:
            url: https://static.digit.in/default/3e3b40843f58f62562fac2fb2026c3adddef3345.jpeg
            caption: "Bruno ligou-se á rede"

#  - alias: Notificar quando Bruno estiver ligado ao wifiariela
#    initial_state: true
#    trigger:
#    - platform: state
#      entity_id: device_tracker.mi_a1
#      from: 'not_home'
#      to: 'home'
#    action:
#      service: notify.telegram
#      data:
#        title: "Bruno "
#        message: "acabou de se ligar á rede."
#        data:
#          photo:
#            url: https://static.digit.in/default/3e3b40843f58f62562fac2fb2026c3adddef3345.jpeg
#            caption: "Bruno ligou-se á rede pelo ariela"

  - alias: Notificar quando Bruno estiver desligado do wifi
    initial_state: true
    trigger:
    - platform: state
      entity_id: person.bruno
      from: 'home'
      to: 'not_home'
    action:
      service: notify.telegram
      data:
        title: "Bruno "
        message: "acabou de se desligar da rede."
        data:
          photo:
            url: https://static.digit.in/default/3e3b40843f58f62562fac2fb2026c3adddef3345.jpeg
            caption: "Bruno desligou-se da rede"

#  - alias: Notificar quando Bruno estiver desligado do wifi ariela
#    initial_state: true
#    trigger:
#    - platform: state
#      entity_id: device_tracker.mi_a1
#      from: 'home'
#      to: 'not_home'
#    action:
#      service: notify.telegram
#      data:
#        title: "Bruno "
#        message: "acabou de se desligar da rede."
#        data:
#          photo:
#            url: https://static.digit.in/default/3e3b40843f58f62562fac2fb2026c3adddef3345.jpeg
#            caption: "Bruno desligou-se da rede pelo ariela"

  - alias: Notificar quando Armanda estiver ligada ao wifi
    initial_state: true
    trigger:
    - platform: state
      entity_id: person.armanda
      from: 'not_home'
      to: 'home'
    action:
      service: notify.telegram
      data:
        title: "Armanda "
        message: "acabou de se ligar á rede."
        data:
          photo:
            url: https://static.digit.in/default/3e3b40843f58f62562fac2fb2026c3adddef3345.jpeg
            caption: "Armanda ligou-se á rede"

  - alias: Notificar quando Armanda estiver desligada do wifi
    initial_state: true
    trigger:
    - platform: state
      entity_id: person.armanda
      from: 'home'
      to: 'not_home'
    action:
      service: notify.telegram
      data:
        title: "Armanda "
        message: "acabou de se desligar da rede."
        data:
          photo:
            url: https://static.digit.in/default/3e3b40843f58f62562fac2fb2026c3adddef3345.jpeg
            caption: "Armanda desligou-se da rede"

  - alias: Notificar quando pai estiver ligado ao wifi
    initial_state: true
    trigger:
    - platform: state
      entity_id: person.armando
      from: 'not_home'
      to: 'home'
    action:
      service: notify.telegram
      data:
        title: "Pai "
        message: "acabou de se ligar á rede."
        data:
          photo:
            url: https://static.digit.in/default/3e3b40843f58f62562fac2fb2026c3adddef3345.jpeg
            caption: "Pai ligou-se á rede"

  - alias: Notificar quando pai estiver desligado do wifi
    initial_state: true
    trigger:
    - platform: state
      entity_id: person.armando
      from: 'home'
      to: 'not_home'
    action:
      service: notify.telegram
      data:
        title: "Pai "
        message: "acabou de se desligar da rede."
        data:
          photo:
            url: https://static.digit.in/default/3e3b40843f58f62562fac2fb2026c3adddef3345.jpeg
            caption: "Pai desligou-se da rede"

#  - alias: ligar sonoff
#    initial_state: false
#    trigger:
#      - platform: state
#        entity_id: group.wifi
#        from: 'home'
#        to: 'not_home'
#    action:
#      - service: switch.turn_on
#        data:
#          entity_id: switch.arvore_de_natal

#  - alias: desligar sonoff
#    initial_state: false
#    trigger:
#      - platform: state
#        entity_id: group.wifi
#        from: 'not_home'
#        to: 'home'
#    action:
#      - service: switch.turn_off
#        data:
#          entity_id: switch.arvore_de_natal

#desligar luzes na ausencia

  - alias: Desligar Luzes na ausencia
    initial_state: true
    trigger:
      - platform: state
        entity_id: group.wifi
        from: 'home'
        to: 'not_home'
    action:
      - service: light.turn_off
        data:
          entity_id:
            - light.yeelight_color1_7811dcaa58c8
            - light.yeelight_color1_7811dce0fe41
            - light.yeelight_color1_7811dce12676
            - light.gateway_light_7811dcb38555
            - light.xiaomi_philips_zhirui
            - light.xiaomi_philips_zhirui_1
            - light.xiaomi_philips_zhirui_2
            - light.led_strip_quarto
            - light.teto_da_sala
            - light.teto_quarto_mafalda
            - light.leds_armario
            - light.downlight_direito
            - light.downlight_esquerdo  
            - light.teto_quarto
            - light.teto_casa_de_banho
            - light.espelho_casa_de_banho
      - delay: '00:00:05'
      - service: light.turn_off
        entity_id: 
          - light.yeelight_color1_7811dc6b9b10
          - light.yeelight_color1_7811dc6b98cb


  - alias: Ligar automação luzes na ausencia
    initial_state: true
    trigger:
      platform: time
      at: '05:00:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: automation.desligar_luzes_na_ausencia
          state: 'off'
    action:
      service: automation.turn_on
      entity_id: automation.desligar_luzes_na_ausencia


#  - alias: Desligar Luzes na ausencia pai
#    initial_state: false
#    trigger:
#      - platform: state
#        entity_id: person.armando
#        from: 'home'
#        to: 'not_home'
#    action:
#      - service: light.turn_off
#        data:
#          entity_id:
#            - light.wc_pai
###############################################################################
#                                                                             #
#                                 G R O U P S                                 #
#                                                                             #
############################################################################### 
group:

  Wifi:     
    name: presenças
    entities: 
      - person.bruno
      - person.armanda